### ISSUE TITLE
Manual updates for post 2.1.6 release

### ISSUE THREAD

**Issue by ldcouto** [overturetool/documentation#1]
A cursory look at the manual revealed the following problems:
- [x] The Welcome page image (Fig. 2.1, pg.6) is outdated. The Welcome page no longer mentions sourceforge etc. (overturetool/overture#403).
- [x] The outline image (Fig. 3.3, pg.9) is outdated. Function icons are now hollow (overturetool/overture#369).
- [x] The POG chapter (chap.9) does not mention the auto-refresh mechanism (overturetool/overture#163). This feature is not in 2.1.6 but it should be in by the time of the next release.
- [x] The GUI Builder feature (overturetool/overture#398) needs to be added. Should it have its own chapter or a section in Chapter 15?
- [x] The command line control of the interpreter (overturetool/overture#351) also needs to be added. Maybe somewhere in chapter 16?
- [x] PVJ: Update Code Generation chapter to reflect most recent changes to this plugin

Feel free to add anything else you find. We can create sub-issues and use this page to track progress towards the entire update.

**Comment by ldcouto** [comment]
We are now in a post-2.2.2 world. Most of these still apply, I believe.

**Comment by ldcouto** [comment]
One more thing...

The manual history should be updated to version 2.2.4. I've gone ahead and done that.

**Comment by peterwvj** [comment]
Cool thanks. Have you settled on the release date? When you have, do you mind posting it here? No valve time please :)

**Comment by ldcouto** [comment]
The plan is to do the merges and build the RC early friday. Then people can
people around with it during the weekend and the release proper will happen
on Monday. Tuesday at the latest.

If you go by valve time, that means sometime in 2020... maybe.

**Comment by ldcouto** [comment]
Another update.

Per https://github.com/overturetool/overture/issues/351, the command line control feature will be removed. There is no need to document this feature anymore.

**Comment by peterwvj** [comment]
A new complete version of the chapter about the Java code generator has been pushed.

**Comment by pglvdm** [comment]
I have also fixed the two screen dumps.

**Comment by ldcouto** [comment]
I've written a section on the GUI builder. I had to take the screenshots on a mac.

**Comment by peterwvj** [comment]
Cool Luis, thanks. I'm still dual booting (although I really want to get completely rid of my Windows) so we can take a Windows screenshot on Monday if you would like.

**Comment by ldcouto** [comment]
I think we'll be pretty busy on Monday but we'll see. They're very simple.
Anyone can duplicate them.

--ldc

**Comment by pglvdm** [comment]
I can take care of these screen dump on my windows PC on Monday…
